In [1]:
import pandas as pd

df_us = pd.read_csv('us.csv')
df_us

            date      cases   deaths
0     2020-01-21          1        0
1     2020-01-22          1        0
2     2020-01-23          1        0
3     2020-01-24          2        0
4     2020-01-25          3        0
...          ...        ...      ...
1153  2023-03-19  103784916  1133826
1154  2023-03-20  103794703  1133964
1155  2023-03-21  103813076  1134177
1156  2023-03-22  103864888  1134913
1157  2023-03-23  103910034  1135343

[1158 rows x 3 columns]

In [15]:
import pandas as pd
if 'county' not in df_us.columns:
    df_us['county'] = 'All Counties'

if 'state' not in df_us.columns:
    df_us['state'] = 'USA'

if 'fips' not in df_us.columns:
    df_us['fips'] = 0 
    
if 'cases' not in df_us.columns:
    df_us['cases'] = 0

if 'deaths' not in df_us.columns:
    df_us['deaths'] = 0

df_us = df_us.drop_duplicates()
df_us

,date,cases,deaths,year,month,day,state,county,fips
0,2020-01-21,1,0,2020,1,21,USA,All Counties,0
1,2020-01-22,1,0,2020,1,22,USA,All Counties,0
2,2020-01-23,1,0,2020,1,23,USA,All Counties,0
3,2020-01-24,2,0,2020,1,24,USA,All Counties,0
4,2020-01-25,3,0,2020,1,25,USA,All Counties,0
...,...,...,...,...,...,...,...,...,...
1153,2023-03-19,103784916,1133826,2023,3,19,USA,All Counties,0
1154,2023-03-20,103794703,1133964,2023,3,20,USA,All Counties,0
1155,2023-03-21,103813076,1134177,2023,3,21,USA,All Counties,0
1156,2023-03-22,103864888,1134913,2023,3,22,USA,All Counties,0
1157,2023-03-23,103910034,1135343,2023,3,23,USA,All Counties,0

In [2]:
df_states = pd.read_csv('us-states.csv')
df_states

             date          state  fips    cases  deaths
0      2020-01-21     Washington    53        1       0
1      2020-01-22     Washington    53        1       0
2      2020-01-23     Washington    53        1       0
3      2020-01-24       Illinois    17        1       0
4      2020-01-24     Washington    53        1       0
...           ...            ...   ...      ...     ...
61937  2023-03-23       Virginia    51  2298300   23782
61938  2023-03-23     Washington    53  1940704   15905
61939  2023-03-23  West Virginia    54   645710    8132
61940  2023-03-23      Wisconsin    55  2014524   16485
61941  2023-03-23        Wyoming    56   185800    2014

[61942 rows x 5 columns]

In [27]:
import pandas as pd

unique_state_county = df_counties[['state', 'county']]
one_county_per_state = unique_state_county.groupby('state').first().reset_index()

df_states_with_county = pd.merge(df_states, one_county_per_state, on='state', how='left')
df_states_with_county = df_states_with_county.drop(columns=['county_x'], errors='ignore')
df_states_with_county = df_states_with_county.rename(columns={'county_y': 'county'})
df_states_with_county

             date          state  fips    cases  deaths     county
0      2020-01-21     Washington  53.0        1       0  Snohomish
1      2020-01-22     Washington  53.0        1       0  Snohomish
2      2020-01-23     Washington  53.0        1       0  Snohomish
3      2020-01-24       Illinois  17.0        1       0       Cook
4      2020-01-24     Washington  53.0        1       0  Snohomish
...           ...            ...   ...      ...     ...        ...
61937  2023-03-23       Virginia  51.0  2298300   23782    Fairfax
61938  2023-03-23     Washington  53.0  1940704   15905  Snohomish
61939  2023-03-23  West Virginia  54.0   645710    8132  Jefferson
61940  2023-03-23      Wisconsin  55.0  2014524   16485       Dane
61941  2023-03-23        Wyoming  56.0   185800    2014   Sheridan

[61942 rows x 6 columns]

In [8]:
df_counties = pd.read_csv('us-counties.csv')
df_counties

               date      county       state     fips  cases  deaths
0        2020-01-21   Snohomish  Washington  53061.0      1     0.0
1        2020-01-22   Snohomish  Washington  53061.0      1     0.0
2        2020-01-23   Snohomish  Washington  53061.0      1     0.0
3        2020-01-24        Cook    Illinois  17031.0      1     0.0
4        2020-01-24   Snohomish  Washington  53061.0      1     0.0
...             ...         ...         ...      ...    ...     ...
2502827  2022-05-13  Sweetwater     Wyoming  56037.0  11088   126.0
2502828  2022-05-13       Teton     Wyoming  56039.0  10074    16.0
2502829  2022-05-13       Uinta     Wyoming  56041.0   5643    39.0
2502830  2022-05-13    Washakie     Wyoming  56043.0   2358    44.0
2502831  2022-05-13      Weston     Wyoming  56045.0   1588    18.0

[2502832 rows x 6 columns]

In [25]:
unique_state_county = df_counties[['state', 'county']]
unique_state_county

              state      county
0        Washington   Snohomish
1        Washington   Snohomish
2        Washington   Snohomish
3          Illinois        Cook
4        Washington   Snohomish
...             ...         ...
2502827     Wyoming  Sweetwater
2502828     Wyoming       Teton
2502829     Wyoming       Uinta
2502830     Wyoming    Washakie
2502831     Wyoming      Weston

[2502832 rows x 2 columns]

In [9]:
df_counties_recent = pd.read_csv('us-counties-recent.csv')
df_counties_recent

             date      county    state     fips  cases  deaths
0      2023-02-22     Autauga  Alabama   1001.0  19732   230.0
1      2023-02-22     Baldwin  Alabama   1003.0  69641   724.0
2      2023-02-22     Barbour  Alabama   1005.0   7451   112.0
3      2023-02-22        Bibb  Alabama   1007.0   8067   109.0
4      2023-02-22      Blount  Alabama   1009.0  18616   261.0
...           ...         ...      ...      ...    ...     ...
97696  2023-03-23  Sweetwater  Wyoming  56037.0  12519   139.0
97697  2023-03-23       Teton  Wyoming  56039.0  12150    16.0
97698  2023-03-23       Uinta  Wyoming  56041.0   6416    43.0
97699  2023-03-23    Washakie  Wyoming  56043.0   2700    51.0
97700  2023-03-23      Weston  Wyoming  56045.0   1906    23.0

[97701 rows x 6 columns]

In [4]:
df_counties_2023 = pd.read_csv('us-counties-2023.csv')
df_counties_2023

              date      county    state     fips  cases  deaths
0       2023-01-01     Autauga  Alabama   1001.0  18961   230.0
1       2023-01-01     Baldwin  Alabama   1003.0  67496   719.0
2       2023-01-01     Barbour  Alabama   1005.0   7027   111.0
3       2023-01-01        Bibb  Alabama   1007.0   7692   108.0
4       2023-01-01      Blount  Alabama   1009.0  17731   260.0
...            ...         ...      ...      ...    ...     ...
267004  2023-03-23  Sweetwater  Wyoming  56037.0  12519   139.0
267005  2023-03-23       Teton  Wyoming  56039.0  12150    16.0
267006  2023-03-23       Uinta  Wyoming  56041.0   6416    43.0
267007  2023-03-23    Washakie  Wyoming  56043.0   2700    51.0
267008  2023-03-23      Weston  Wyoming  56045.0   1906    23.0

[267009 rows x 6 columns]

In [5]:
df_counties_2022 = pd.read_csv('us-counties-2022.csv')
df_counties_2022

               date      county    state     fips  cases  deaths
0        2022-01-01     Autauga  Alabama   1001.0  11018   160.0
1        2022-01-01     Baldwin  Alabama   1003.0  39911   593.0
2        2022-01-01     Barbour  Alabama   1005.0   3860    81.0
3        2022-01-01        Bibb  Alabama   1007.0   4533    95.0
4        2022-01-01      Blount  Alabama   1009.0  11256   198.0
...             ...         ...      ...      ...    ...     ...
1188037  2022-12-31  Sweetwater  Wyoming  56037.0  12410   136.0
1188038  2022-12-31       Teton  Wyoming  56039.0  12010    16.0
1188039  2022-12-31       Uinta  Wyoming  56041.0   6305    43.0
1188040  2022-12-31    Washakie  Wyoming  56043.0   2721    47.0
1188041  2022-12-31      Weston  Wyoming  56045.0   1880    22.0

[1188042 rows x 6 columns]

In [6]:
df_counties_2021 = pd.read_csv('us-counties-2021.csv')
df_counties_2021

               date      county    state     fips  cases  deaths
0        2021-01-01     Autauga  Alabama   1001.0   4239    50.0
1        2021-01-01     Baldwin  Alabama   1003.0  13823   169.0
2        2021-01-01     Barbour  Alabama   1005.0   1517    33.0
3        2021-01-01        Bibb  Alabama   1007.0   1854    46.0
4        2021-01-01      Blount  Alabama   1009.0   4693    63.0
...             ...         ...      ...      ...    ...     ...
1185368  2021-12-31  Sweetwater  Wyoming  56037.0   8320   107.0
1185369  2021-12-31       Teton  Wyoming  56039.0   5950    14.0
1185370  2021-12-31       Uinta  Wyoming  56041.0   4154    31.0
1185371  2021-12-31    Washakie  Wyoming  56043.0   1879    37.0
1185372  2021-12-31      Weston  Wyoming  56045.0   1254    14.0

[1185373 rows x 6 columns]

In [7]:
df_counties_2020 = pd.read_csv('us-counties-2020.csv')
df_counties_2020

              date      county       state     fips  cases  deaths
0       2020-01-21   Snohomish  Washington  53061.0      1     0.0
1       2020-01-22   Snohomish  Washington  53061.0      1     0.0
2       2020-01-23   Snohomish  Washington  53061.0      1     0.0
3       2020-01-24        Cook    Illinois  17031.0      1     0.0
4       2020-01-24   Snohomish  Washington  53061.0      1     0.0
...            ...         ...         ...      ...    ...     ...
884732  2020-12-31  Sweetwater     Wyoming  56037.0   2966    16.0
884733  2020-12-31       Teton     Wyoming  56039.0   2138     4.0
884734  2020-12-31       Uinta     Wyoming  56041.0   1558     7.0
884735  2020-12-31    Washakie     Wyoming  56043.0    780    19.0
884736  2020-12-31      Weston     Wyoming  56045.0    476     2.0

[884737 rows x 6 columns]

In [30]:
df_all_counties = pd.concat([
    df_states_with_county,
    df_counties,
    df_counties_recent,
    df_counties_2023,
    df_counties_2022,
    df_counties_2021,
    df_counties_2020
], ignore_index=True)
df_all_counties

               date       state     fips  cases  deaths      county
0        2020-01-21  Washington     53.0      1     0.0   Snohomish
1        2020-01-22  Washington     53.0      1     0.0   Snohomish
2        2020-01-23  Washington     53.0      1     0.0   Snohomish
3        2020-01-24    Illinois     17.0      1     0.0        Cook
4        2020-01-24  Washington     53.0      1     0.0   Snohomish
...             ...         ...      ...    ...     ...         ...
6187631  2020-12-31     Wyoming  56037.0   2966    16.0  Sweetwater
6187632  2020-12-31     Wyoming  56039.0   2138     4.0       Teton
6187633  2020-12-31     Wyoming  56041.0   1558     7.0       Uinta
6187634  2020-12-31     Wyoming  56043.0    780    19.0    Washakie
6187635  2020-12-31     Wyoming  56045.0    476     2.0      Weston

[6187636 rows x 6 columns]

In [31]:
df_all_counties['date'] = pd.to_datetime(df_all_counties['date'])

df_all_counties['year'] = df_all_counties['date'].dt.year
df_all_counties['month'] = df_all_counties['date'].dt.month
df_all_counties['day'] = df_all_counties['date'].dt.day
df_all_counties

,date,state,fips,cases,deaths,county,year,month,day
0,2020-01-21,Washington,53.0,1,0.0,Snohomish,2020,1,21
1,2020-01-22,Washington,53.0,1,0.0,Snohomish,2020,1,22
2,2020-01-23,Washington,53.0,1,0.0,Snohomish,2020,1,23
3,2020-01-24,Illinois,17.0,1,0.0,Cook,2020,1,24
4,2020-01-24,Washington,53.0,1,0.0,Snohomish,2020,1,24
...,...,...,...,...,...,...,...,...,...
6187631,2020-12-31,Wyoming,56037.0,2966,16.0,Sweetwater,2020,12,31
6187632,2020-12-31,Wyoming,56039.0,2138,4.0,Teton,2020,12,31
6187633,2020-12-31,Wyoming,56041.0,1558,7.0,Uinta,2020,12,31
6187634,2020-12-31,Wyoming,56043.0,780,19.0,Washakie,2020,12,31
6187635,2020-12-31,Wyoming,56045.0,476,2.0,Weston,2020,12,31

In [32]:
df_us_aligned = df_us[df_all_counties.columns]
df_combined = pd.concat([df_all_counties, df_us_aligned], ignore_index=True)
df_combined

,date,state,fips,cases,deaths,county,year,month,day
0,2020-01-21,Washington,53.0,1,0.0,Snohomish,2020,1,21
1,2020-01-22,Washington,53.0,1,0.0,Snohomish,2020,1,22
2,2020-01-23,Washington,53.0,1,0.0,Snohomish,2020,1,23
3,2020-01-24,Illinois,17.0,1,0.0,Cook,2020,1,24
4,2020-01-24,Washington,53.0,1,0.0,Snohomish,2020,1,24
...,...,...,...,...,...,...,...,...,...
6188789,2023-03-19,USA,0.0,103784916,1133826.0,All Counties,2023,3,19
6188790,2023-03-20,USA,0.0,103794703,1133964.0,All Counties,2023,3,20
6188791,2023-03-21,USA,0.0,103813076,1134177.0,All Counties,2023,3,21
6188792,2023-03-22,USA,0.0,103864888,1134913.0,All Counties,2023,3,22
6188793,2023-03-23,USA,0.0,103910034,1135343.0,All Counties,2023,3,23

In [34]:
print("Jumlah NaN per kolom:")
print(df_combined[['cases', 'deaths', 'county', 'state', 'fips']].isna().sum())

Jumlah NaN per kolom:
cases          0
deaths    142042
county         0
state          0
fips       59935
dtype: int64

In [44]:
df_combined['deaths'] = df_combined['deaths'].fillna(0)
df_combined['fips'] = df_combined['fips'].fillna(0)

In [45]:
print("Jumlah NaN per kolom:")
print(df_combined[['cases', 'deaths', 'county', 'state', 'fips']].isna().sum())

Jumlah NaN per kolom:
cases     0
deaths    0
county    0
state     0
fips      0
dtype: int64

In [38]:
nan_loc = df_combined[df_combined['county'].isna() | df_combined['state'].isna()]
print("Baris dengan NaN di kolom county atau state:")
nan_loc

Baris dengan NaN di kolom county atau state:

Empty DataFrame
Columns: [date, state, fips, cases, deaths, county, year, month, day]
Index: []

In [37]:
neg_val = df_combined[(df_combined['cases'] < 0) | (df_combined['deaths'] < 0)]
print(f"Jumlah baris dengan nilai negatif di cases atau deaths: {len(neg_val)}")
neg_val

Jumlah baris dengan nilai negatif di cases atau deaths: 0

Empty DataFrame
Columns: [date, state, fips, cases, deaths, county, year, month, day]
Index: []

In [43]:
duplicates = df_combined[df_combined.duplicated()]
print(f"Jumlah data duplikat: {len(duplicates)}")
duplicates

#ga di hapus, karena terjadi di county berbedaa beda, ya ga si

Jumlah data duplikat: 2600420

,date,state,fips,cases,deaths,county,year,month,day
2831783,2023-02-22,Alabama,1001.0,19732,230.0,Autauga,2023,2,22
2831784,2023-02-22,Alabama,1003.0,69641,724.0,Baldwin,2023,2,22
2831785,2023-02-22,Alabama,1005.0,7451,112.0,Barbour,2023,2,22
2831786,2023-02-22,Alabama,1007.0,8067,109.0,Bibb,2023,2,22
2831787,2023-02-22,Alabama,1009.0,18616,261.0,Blount,2023,2,22
...,...,...,...,...,...,...,...,...,...
6187631,2020-12-31,Wyoming,56037.0,2966,16.0,Sweetwater,2020,12,31
6187632,2020-12-31,Wyoming,56039.0,2138,4.0,Teton,2020,12,31
6187633,2020-12-31,Wyoming,56041.0,1558,7.0,Uinta,2020,12,31
6187634,2020-12-31,Wyoming,56043.0,780,19.0,Washakie,2020,12,31
6187635,2020-12-31,Wyoming,56045.0,476,2.0,Weston,2020,12,31

In [47]:
df_combined.to_csv('covid19.csv', index=False)

In [48]:
df= pd.read_csv('covid19.csv')
df

,date,state,fips,cases,deaths,county,year,month,day
0,2020-01-21,Washington,53.0,1,0.0,Snohomish,2020,1,21
1,2020-01-22,Washington,53.0,1,0.0,Snohomish,2020,1,22
2,2020-01-23,Washington,53.0,1,0.0,Snohomish,2020,1,23
3,2020-01-24,Illinois,17.0,1,0.0,Cook,2020,1,24
4,2020-01-24,Washington,53.0,1,0.0,Snohomish,2020,1,24
...,...,...,...,...,...,...,...,...,...
6188789,2023-03-19,USA,0.0,103784916,1133826.0,All Counties,2023,3,19
6188790,2023-03-20,USA,0.0,103794703,1133964.0,All Counties,2023,3,20
6188791,2023-03-21,USA,0.0,103813076,1134177.0,All Counties,2023,3,21
6188792,2023-03-22,USA,0.0,103864888,1134913.0,All Counties,2023,3,22
6188793,2023-03-23,USA,0.0,103910034,1135343.0,All Counties,2023,3,23

In [84]:
nan_summary = df[["date", "state", "fips", "cases", "deaths", "county", "year", "month", "day"]].isna().sum().to_frame(name='NaN Count')
nan_summary['% NaN'] = (nan_summary['NaN Count'] / len(df)) * 100
nan_summary

        NaN Count  % NaN
date            0    0.0
state           0    0.0
fips            0    0.0
cases           0    0.0
deaths          0    0.0
county          0    0.0
year            0    0.0
month           0    0.0
day             0    0.0

In [97]:
print(df.dtypes)

date       object
state      object
fips      float64
cases       int64
deaths    float64
county     object
year        int64
month       int64
day         int64
dtype: object

In [107]:
#atasi fips yg float
df["fips"] = df["fips"].fillna(0).astype(float).round().astype(int)

In [108]:
#atasi death yg float
df["deaths"] = df["deaths"].fillna(0).round().astype(int)

In [109]:
df.dtypes

date      object
state     object
fips       int64
cases      int64
deaths     int64
county    object
year       int64
month      int64
day        int64
dtype: object

In [110]:
df

,date,state,fips,cases,deaths,county,year,month,day
0,2020-01-21,Washington,53,1,0,Snohomish,2020,1,21
1,2020-01-22,Washington,53,1,0,Snohomish,2020,1,22
2,2020-01-23,Washington,53,1,0,Snohomish,2020,1,23
3,2020-01-24,Illinois,17,1,0,Cook,2020,1,24
4,2020-01-24,Washington,53,1,0,Snohomish,2020,1,24
...,...,...,...,...,...,...,...,...,...
6188789,2023-03-19,USA,0,103784916,1133826,All Counties,2023,3,19
6188790,2023-03-20,USA,0,103794703,1133964,All Counties,2023,3,20
6188791,2023-03-21,USA,0,103813076,1134177,All Counties,2023,3,21
6188792,2023-03-22,USA,0,103864888,1134913,All Counties,2023,3,22
6188793,2023-03-23,USA,0,103910034,1135343,All Counties,2023,3,23

In [ ]:
#CUBE

In [78]:
import atoti as tt
import pandas as pd
from sqlalchemy import create_engine

In [63]:
import pandas as pd
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [95]:
session = tt.Session.start()

In [111]:
store = session.read_pandas(
    df,
    table_name="covid19_dataa",
    data_types={
        "date": tt.type.STRING,    
        "state": tt.type.STRING,
        "fips": tt.type.INT,       
        "cases": tt.type.INT,           
        "deaths": tt.type.INT,       
        "county": tt.type.STRING,
        "year": tt.type.INT,
        "month": tt.type.INT,
        "day": tt.type.INT,
    }
)

In [112]:
cube = session.create_cube(store)
h = cube.hierarchies
l = cube.levels
m = cube.measures

In [113]:
h

{('covid19_dataa', 'state'): <atoti.hierarchy.Hierarchy object at 0x000001E0A3FE6A80>, ('covid19_dataa', 'county'): <atoti.hierarchy.Hierarchy object at 0x000001E0A4656AE0>, ('covid19_dataa', 'date'): <atoti.hierarchy.Hierarchy object at 0x000001E0A4889910>}

In [114]:
l

{('covid19_dataa', 'state', 'state'): <atoti.level.Level object at 0x000001E0A46E7E00>, ('covid19_dataa', 'county', 'county'): <atoti.level.Level object at 0x000001E0A46E61E0>, ('covid19_dataa', 'date', 'date'): <atoti.level.Level object at 0x000001E0A46E4110>}

In [115]:
m

{'day.MEAN': <atoti.measure.Measure object at 0x000001E0A4650950>, 'cases.MEAN': <atoti.measure.Measure object at 0x000001E0A4653320>, 'month.SUM': <atoti.measure.Measure object at 0x000001E0A4650F80>, 'year.SUM': <atoti.measure.Measure object at 0x000001E0A46531D0>, 'fips.MEAN': <atoti.measure.Measure object at 0x000001E0A4651BB0>, 'month.MEAN': <atoti.measure.Measure object at 0x000001E0A4651B20>, 'day.SUM': <atoti.measure.Measure object at 0x000001E0A4651A00>, 'deaths.MEAN': <atoti.measure.Measure object at 0x000001E0A4652CF0>, 'year.MEAN': <atoti.measure.Measure object at 0x000001E0A4653350>, 'contributors.COUNT': <atoti.measure.Measure object at 0x000001E0A46526F0>, 'fips.SUM': <atoti.measure.Measure object at 0x000001E0A46512E0>, 'cases.SUM': <atoti.measure.Measure object at 0x000001E0A46513A0>, 'update.TIMESTAMP': <atoti.measure.Measure object at 0x000001E0A4653410>, 'deaths.SUM': <atoti.measure.Measure object at 0x000001E0A4650EC0>}